name: Build index

on:
    workflow_dispatch:
    push:
      branches:
        - components
      paths:
        - 'components/**.yaml'
        - 'index.json'

permissions:
    contents: write

jobs:
    build-index:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false

        steps:
        - name: Checkout components
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
            ref: 'components'
            path: components

        - name: Checkout main
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
            ref: 'main'
            path: main

        - name: Checkout gh-page
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
            ref: 'gh-page'
            path: gh-page

        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install yaml
          run: pip install pyyaml

        - name: Build index
          run: python -B components/.github/scripts/build_index.py --build-branch components --deploy-branch main

        - name: Get last commit message - components
          id: last-commit-message-components
          run: echo "msg=$(git -C components log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Get last commit message - main
          id: last-commit-message-main
          run: echo "msg=$(git -C main log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Get last commit message - gh-page
          id: last-commit-message-gh-page
          run: echo "msg=$(git -C gh-page log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: copy yaml
          run: cp -r components/components/*.yaml main/components/

        - name: copy yaml
          run: cp -r components/components/*.yaml gh-page/components/

        - name: copy yaml
          run: cp -r main/index.json gh-page/index.json

        - name: Commit - main
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: ${{ steps.last-commit-message-main.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json components/*.yaml'
            push_options: '--force'
            skip_fetch: true
            repository: main

        - name: Commit - gh-page
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: ${{ steps.last-commit-message-gh-page.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json components/*.yaml'
            push_options: '--force'
            skip_fetch: true
            repository: gh-page

        - name: Commit - components
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: ${{ steps.last-commit-message-components.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json'
            push_options: '--force'
            skip_fetch: true
            repository: components